[package]
name = "didp-mpi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dypdl = "0.8"
dypdl-heuristic-search = "0.8"
didp-yaml = "0.8"
mpi = "0.8"
zerocopy = "0.7"
yaml-rust = "0.4"
linked-hash-map = "0.5"
rustc-hash = "1.1"
rand = "0.8"
rand_pcg = "0.3"
serde_yaml = "0.9"
serde = "1.0"
memoffset = "0.9"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[profile.release]
lto = true
codegen-units = 1

[profile.release-with-debug]
inherits = "release"
debug = true
